name: test-fmt

on:
  push:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: clang-format-lint-action
      uses: frroossst/clang-format-lint-action@v4
      with:
        filePath: ./CPP_flight_computer_program/src/*
